### ISSUE TITLE
Corrfunc error when running on a very sparse catalog

### ISSUE THREAD

**Issue by tmcclintock** [rafaelgm9/2pcf_jk#2]
I'm not sure what's happening, but when I run this very minimal example with a very sparse catalog (~2600 halos in a (1050 Mpc/h)^3 box) I get an error from Corrfunc. Here is the error:
```
Error in file: ../../utils/gridlink_impl_double.c	func: gridlink_index_particles_double	line: 403 with expression `ix >= 0 && ix < nmesh_x'
ix=-2147483648 must be within [0,1)
Hopefully, input validation. Otherwise, bug in code: please email Manodeep Sinha <manodeep@gmail.com>
Traceback (most recent call last):
  File "minimal_example.py", line 8, in <module>
    meanxi_i, cov, xi_i, xi = auto_correlation.auto_tpcf_jk(d1 = pos, boxsize = 1050., gridsize = 1050./10., minsep = 0.1, maxsep = 80., nbins = 50, nthreads = 1, jk_estimates = True)
  File "/afs/slac.stanford.edu/u/ki/tmcclint/projects/HH_scripts/auto_correlation.py", line 209, in auto_tpcf_jk
    ddpairs = auto_DD_jk(d1, d1_id, boxsize, gridsize, minsep, maxsep, nbins, nthreads)
  File "/afs/slac.stanford.edu/u/ki/tmcclint/projects/HH_scripts/auto_correlation.py", line 102, in auto_DD_jk
    periodic=False, verbose=False)
  File "/nfs/slac/g/ki/ki22/cosmo/tmcclint/anaconda2/lib/python2.7/site-packages/Corrfunc-2.0.1-py2.7-linux-x86_64.egg/Corrfunc/theory/DD.py", line 237, in DD
    isa=integer_isa, **kwargs)
TypeError: 'NoneType' object is not iterable
```

And here is the script:
```python
import os, sys
import numpy as np
import auto_correlation

pos = np.loadtxt("test_positions.txt")

meanxi_i, cov, xi_i, xi = auto_correlation.auto_tpcf_jk(d1 = pos, boxsize = 1050., gridsize = 1050./10., minsep = 0.1, maxsep = 80., nbins = 50, nthreads = 1, jk_estimates = True)
```

The catalog to try this is [here].(https://github.com/rafaelgm9/2pcf_jk/files/2129328/test_positions.txt)

Any idea what is going on?

**Comment by tmcclintock** [comment]
Tagging @manodeep.
